[WFTC-108] Unit tests draft
wildfly/wildfly-transaction-client pull request #136
Opened 2022-12-20 11:12 UTC by tadamski

2023-03-28 14:13 UTC, rachmatowicz commented on src/test/java/org/wildfly/transaction/client/DummyServer.java
> +public class DummyServer implements AutoCloseable {
Descriptive comments to describe the purpose of this class?

2023-03-28 14:13 UTC, rachmatowicz commented on src/test/java/org/wildfly/transaction/client/LocalUserTransactionTestCase.java
> +public class LocalUserTransactionTestCase {
Descriptive comments to describe the purpose of this set of tests and what it validates?

2023-03-28 14:13 UTC, rachmatowicz commented on src/test/java/org/wildfly/transaction/client/LocalUserTransactionTestCase.java
> +    public void simpleCommitTest() throws Exception {
Descriptive comments to describe the expectations of the test? These tests are effectively the specification of behaviour for the transaction client, and help clarify the expected behaviour of different aspects of the library.

2023-03-28 14:13 UTC, rachmatowicz commented on src/test/java/org/wildfly/transaction/client/RemoteUserTransactionTestCase.java
> +public class RemoteUserTransactionTestCase {
Descriptive comments to describe the purpose of this suite of tests?

2023-03-28 14:13 UTC, rachmatowicz commented on src/test/java/org/wildfly/transaction/client/provider/jboss/TestExtendedJBossXATerminator.java
> +public class TestExtendedJBossXATerminator implements ExtendedJBossXATerminator {
Descriptive comments to describe the purpose of this test class?

2023-03-28 14:13 UTC, rachmatowicz commented on src/test/java/org/wildfly/transaction/client/provider/jboss/TestImportedTransaction.java
> +public class TestImportedTransaction extends TestTransaction implements ImportedTransaction {
Descriptive comments to describe the purpose of this test class?

2023-03-28 14:13 UTC, rachmatowicz commented on src/test/java/org/wildfly/transaction/client/provider/jboss/TestTransaction.java
> +public class TestTransaction implements Transaction {
Descriptive comments to describe the purpose of this test class?

2023-03-28 14:13 UTC, rachmatowicz commented on src/test/java/org/wildfly/transaction/client/provider/jboss/TestTransactionManager.java
> +public class TestTransactionManager implements TransactionManager {
Descriptive comments to describe the purpose of this test class?

2023-03-28 14:13 UTC, rachmatowicz commented on src/test/java/org/wildfly/transaction/client/provider/jboss/TestTransactionProvider.java
> +public class TestTransactionProvider extends JBossLocalTransactionProvider {
Descriptive comments to describe the function of this test class?

2023-03-28 14:14 UTC, rachmatowicz commented
Descriptive comments are important here as this is perhaps the only place where users will be able to understand the contracts between a user application and the wildfly-transaction-client abstractions.

2023-04-21 16:55 UTC, tadamski commented on src/test/java/org/wildfly/transaction/client/LocalUserTransactionTestCase.java
> +    public void simpleCommitTest() throws Exception {
fixed

2023-04-21 16:55 UTC, tadamski commented on src/test/java/org/wildfly/transaction/client/RemoteUserTransactionTestCase.java
> +public class RemoteUserTransactionTestCase {
fixed

2023-04-21 16:55 UTC, tadamski commented on src/test/java/org/wildfly/transaction/client/provider/jboss/TestExtendedJBossXATerminator.java
> +public class TestExtendedJBossXATerminator implements ExtendedJBossXATerminator {
fixed

2023-04-21 16:55 UTC, tadamski commented on src/test/java/org/wildfly/transaction/client/provider/jboss/TestImportedTransaction.java
> +public class TestImportedTransaction extends TestTransaction implements ImportedTransaction {
fixed

2023-04-21 16:56 UTC, tadamski commented on src/test/java/org/wildfly/transaction/client/provider/jboss/TestTransaction.java
> +public class TestTransaction implements Transaction {
fixed

2023-04-21 16:56 UTC, tadamski commented on src/test/java/org/wildfly/transaction/client/provider/jboss/TestTransactionManager.java
> +public class TestTransactionManager implements TransactionManager {
fixed

2023-04-21 16:56 UTC, tadamski commented on src/test/java/org/wildfly/transaction/client/provider/jboss/TestTransactionProvider.java
> +public class TestTransactionProvider extends JBossLocalTransactionProvider {
fixed

2023-04-21 16:57 UTC, tadamski commented
@rachmatowicz I have added the descriptions.

2023-05-30 20:10 UTC, rachmatowicz requested changes
This is a nice start to our transaction client testing, thanks Tomasz. 
For the future, we could consider the following:
- more extensive coverage of common scenarios: for each of the three scenarios (standalone client -> server, server-client -> server, server-client -> server1, server2), to have more complete coverage would be to test the scenarios commit, rollback, rollback only and recovery in each scenario. 
- more extensive coverage of exception handling: the code paths exercised here really focus on non-exceptional behavior; we may want to add to this by using Byteman rules to throw exceptions at specific strategic points in the execution and test that the framework responds as expected

2023-05-30 20:10 UTC, rachmatowicz commented on src/test/java/org/wildfly/transaction/client/provider/jboss/TestXAResource.java
> +public class TestXAResource implements XAResource {
Maybe not for now, but it would be nice to validate that during a 2PC interaction between the TransactionManager and a remote XAResource, the correct sequence of servers-side operations (prepare, commit, rollback) were being performed during the execution of the protocol.

2023-05-30 20:10 UTC, rachmatowicz commented on src/test/java/org/wildfly/transaction/client/provider/jboss/TestTransactionProvider.java
> +    public void registerInterposedSynchronization(Transaction transaction, Synchronization sync) throws IllegalArgumentException {
Maybe not for now, but in a future version, validating that any registered synchronizations are being performed before and after completion in the manner expected during the 2PC protocol.

2023-05-31 13:58 UTC, tadamski commented on src/test/java/org/wildfly/transaction/client/LocalUserTransactionTestCase.java
> +public class LocalUserTransactionTestCase {
done

2023-05-31 14:46 UTC, tadamski commented on src/test/java/org/wildfly/transaction/client/RemoteUserTransactionTestCase.java
> +    public void testCommit() throws Exception {
IIUC in local case scenario wildfly-transaction-client is working only on server side and is delegating to the underlying (same VM) transaction manager (Narayana). In the unit test Narayana is mocked and checked, so I think this is fine.

I agree that I would be good to check that in remote scenario though. Here the mock is dummy server which is just a dev/null exivalent currently. Making such checks would require making the dummyserver aware of the protocol. I'm not sure it is feasible to extend (and later maintain) this mock class to be protocol aware. Maybe a integration test would be a better place for that check?

2023-05-31 14:47 UTC, tadamski commented on src/test/java/org/wildfly/transaction/client/LocalUserTransactionTestCase.java
> +    @Test
I have replied above.

2023-05-31 14:50 UTC, tadamski commented on src/test/java/org/wildfly/transaction/client/LocalUserTransactionTestCase.java
> +        final LocalTransactionContext transactionContext = new LocalTransactionContext(new TestTransactionProvider(500, Path.of("./target")));
My understanding here, is that local test case happens only on server side.

2023-05-31 15:34 UTC, tadamski commented on src/test/java/org/wildfly/transaction/client/provider/jboss/TestTransaction.java
> +        ACTIVE, SUSPENDED, PREPARED, COMMITTED, ROLLED_BACK
this is a bug; the code was actually left in a draft form; I have removed suspended state, matched other names to jpa api, and added marked_rollback state

2023-05-31 17:06 UTC, tadamski commented on src/test/java/org/wildfly/transaction/client/provider/jboss/TestTransaction.java
> +    void putLocalResource(Object key, Object value) {
I don't recall why I added those two kinds of putResource methods. I looked at some hints in provider implementation and see also nothing of this kind. I'm reverting it for now as the tests pass normally. If later I recall what it was needed for while extending the tests I will readd it.

2023-05-31 21:09 UTC, tadamski commented on src/test/java/org/wildfly/transaction/client/provider/jboss/TestXAResourceRecoveryRegistry.java
> +public class TestXAResourceRecoveryRegistry implements XAResourceRecoveryRegistry {
OK. Will create a JIRA for that specific enhancement.

2023-05-31 21:24 UTC, tadamski commented on src/test/java/org/wildfly/transaction/client/provider/jboss/TestXAResourceRecoveryRegistry.java
> +public class TestXAResourceRecoveryRegistry implements XAResourceRecoveryRegistry {
created [WFTC-122](https://issues.redhat.com/browse/WFTC-122)

2023-06-01 14:03 UTC, tadamski commented on src/test/java/org/wildfly/transaction/client/provider/jboss/TestTransactionProvider.java
> +    public void registerInterposedSynchronization(Transaction transaction, Synchronization sync) throws IllegalArgumentException {
created [WFTC-123](https://issues.redhat.com/browse/WFTC-123)

2023-06-01 14:52 UTC, tadamski commented
@rachmatowicz Thanks for the thorough review.

I have fixed the small issues that you mentioned about. Regarding more complex extensions: I agree that they should be done but I think we should open the jiras for them and move forward with merging this initial PR.

Regarding those extensions I have created the following jiras:
https://issues.redhat.com/browse/WFTC-122 - extending XAResourceRecoveryRegistry to be usable in recovery scenarios
https://issues.redhat.com/browse/WFTC-123 - extending 2PC testsing
https://issues.redhat.com/browse/WFTC-124 - more comprehensive testing of basic scenarios 
https://issues.redhat.com/browse/WFTC-125 - more comprehensive testing of exceptional scenarios (using Byteman)

2023-06-13 13:34 UTC, merged